server.port=8090
spring.datasource.url=jdbc:sqlite:C:\workspace\SpringBootSample\demo\src\main\java\com\example\demo\model\construct.db
spring.datasource.driver-class-name = org.sqlite.JDBC
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update